---
title: "Homework 6"
author: "Mufeng Xu"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(modelr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

### Problem 1

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    resolution = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1)
  ) %>% 
  filter(
    victim_race %in% c("White", "Black"),
    city_state != "Tulsa, AL") %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```


Start with one city.

```{r}
baltimore_df =
  homicide_df %>% 
  filter(city_state == "Baltimore, MD")
glm(resolution ~ victim_age + victim_race + victim_sex, 
    data = baltimore_df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```


Try this across cities.

```{r}
models_results_df = 
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = 
      map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI")) 
```

```{r}
models_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


# Problem 2

### Load and clean data for regression analysis

```{r}
baby_df = 
  read_csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = case_when(
      babysex == 1 ~ "Male",
      babysex == 2 ~ "Female"
    ),
    frace = case_when(
      frace == 1 ~ "White",
      frace == 2 ~ "Black",
      frace == 3 ~ "Asian",
      frace == 4 ~ "Puerto Rican",
      frace == 8 ~ "Other",
      frace == 9 ~ "Unknown"
    ),
    mrace = case_when(
      mrace == 1 ~ "White",
      mrace == 2 ~ "Black",
      mrace == 3 ~ "Asian",
      mrace == 4 ~ "Puerto Rican",
      mrace == 8 ~ "Other"
    ),
    malform = case_when(
      malform == 0 ~ "absent",
      malform == 1 ~ "present"
    ),
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    mrace = as.factor(mrace),
    malform = as.factor(malform)
  ) %>% 
  drop_na()
```

### Select a model

```{r}
# Stepwise Elimination
model_selection = 
  lm(bwt ~ ., data = baby_df) %>% 
  step(., direction = "both") %>% 
  broom::tidy()

# Final model selection
model = 
  lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = baby_df)

model %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```

### Residual Plots

```{r}
baby_df %>% 
  add_residuals(model) %>% 
  add_predictions(model) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(color = "orange", alpha = 0.4) +
  labs(
    title = "Residual vs. fitted values for the stepwise eliminated model",
    x = "Predictions",
    y = "Residuals"
  )
```


### Other two models

```{r}
model_1 = lm(bwt ~ blength + gaweeks, data = baby_df)
model_2 = lm(bwt ~ bhead * blength * babysex, data = baby_df)

model_1 %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)

model_2 %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)

```

### Cross Validation

```{r}
cv_df =
  crossv_mc(baby_df, 200)

cv_df = 
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )

# fit the models and get RMSEs
cv_df = 
  cv_df %>% 
  mutate(
    fit_selected = map(
      .x = train, ~lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = .x)),
    fit_1 = map(
      .x = train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    fit_2 = map(
      .x = train, ~lm(bwt ~ bhead * blength * babysex, data = .x)
    )
  ) %>% 
  mutate(
    rmse_fit_selected = map2_dbl(.x = fit_selected, .y = test, ~rmse(model = .x, data = .y)),
    rmse_fit_1 = map2_dbl(.x = fit_1, .y = test, ~rmse(model = .x, data = .y)),
    rmse_fit_2 = map2_dbl(.x = fit_2, .y = test, ~rmse(model = .x, data = .y))
  )

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>% 
  ggplot(aes(x = model, y = rmse)) +
  geom_violin() +
  labs(
    title = "Cross Validation Violin Plots",
    x = "Models",
    y = "RMSE"
  )

```


# Problem 3

### Load the data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

### Bootstrapping

```{r}
bootstrap_results = 
  weather_df %>% 
  bootstrap(5000, id = "strap_number") %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    result_tidy = map(models, broom::tidy),
    result_glance = map(models, broom::glance)) %>% 
  select(strap_number, result_tidy, result_glance) %>% 
  unnest(result_tidy, result_glance) %>% 
  select(strap_number, term, estimate, r.squared)
```

### R^2 distribution plot

```{r}
rsqu_plot = 
  bootstrap_results %>% 
  ggplot(aes(x = r.squared)) +
  geom_density(fill = "orange", alpha = 0.6) +
  labs(
    title = "Distribution plot of estimated R^2",
    x = "Estimated R^2"
  )

rsqu_plot
```

### Log(beta0 * beta1) distribution plot

```{r}
log_df = 
  bootstrap_results %>% 
  pivot_wider(
    names_from = "term",
    values_from = "estimate"
  ) %>% 
  rename(beta_0 = "(Intercept)",
         beta_1 = "tmin") %>% 
  mutate(
    log = log(beta_0 * beta_1)
  )

log_plot = 
  log_df %>% 
  ggplot(aes(x = log)) +
  geom_density(fill = "pink", alpha = 0.6) +
  labs(
    title = "Distribution plot of log(beta0 * beta1)",
    x = "log(beta0 * beta1)"
  )

log_plot
```

### 95% Confidence Interval

```{r}
ci_df = 
  log_df %>% 
  summarise(
    rsq_lower = quantile(r.squared, 0.025),
    rsq_upper = quantile(r.squared, 0.975),
    log_lower = quantile(log, 0.025),
    log_upper = quantile(log, 0.975)
  ) %>% 
  pivot_longer(rsq_lower:log_upper,
               names_to = "CI",
               values_to = "Boundary") %>% 
  separate(CI, into = c("Subject", "CI"), sep = "_") %>% 
  pivot_wider(
    names_from = "CI", 
    values_from = "Boundary") %>% 
  knitr::kable(digits = 4)

ci_df

```














